### PR TITLE
increase azure vm size

### PR DESCRIPTION
**Pull request by staticvoid255**
current size (Standard_A8_v2) result in the install timing out and failing, a bigger size (Standard_F8s_v2) solved this issue for me

### CODE REVIEW

**Comment by diabhey** [comment]
@staticvoid255 : I would prefer not to increase the VM size in order to keep the footprint low. I am assuming yours was a one-off case?

**Comment by staticvoid255** [comment]
Yesterday I tried multiple times to install Otomi on a cluster of A8 nodes and every time the install timed out unfortunately. Possible that increasing the node count would work either but it's more likely that the root of the issue is size. I also encountered the same issue the first time I installed Otomi after joining and had to do the same (under the recommendation of @j-zimnowoda ). Might also be worth investigating if this happens on similarly sized clusters from different providers, but as it stands the current AKS quickstart doesn't work.

**Comment by diabhey** [comment]
I will merge the changes for now so that we don't block anyone from trying it out. We surely need to iron this out properly in the future.

**Comment by staticvoid255** [comment]
Cool. Might mean adjusting the resource requests for the installer job, I'll come back to this at a later stage.

**Pull request merged**
